### ISSUE TITLE
403 error

### ISSUE THREAD

**Issue by Eibich** [soerenuhrbach/vscode-deepl#12]
Every translation drops a 403

**Comment by soerenuhrbach** [comment]
Hi,

Is your API-Key correct? 
Do you use the correct version? Please make sure you use the free version if you don't use the paid deepl plan.

**Comment by Eibich** [comment]
Iam using: DeepL API Free. Hope this is the correct one.

Also generated a new API key and tried to use it. Still no luck.

**Comment by soerenuhrbach** [comment]
Hey @Eibich,

I just tested a few translations mit my api key. It's works fine.

Unfortunately I can't help you. Just try to validate your api key configuration. 

Best regards 
Sören

**Comment by Hamzelot** [comment]
I have the same problem. 

I just created a DeepL Free User and entered the API key.
The format of this key is as follows, X are changed with other key.

XXXXXXXX-XXXX-XXXX-XXXXXXXXX:fx

DeepL for Visual Studio Code = v1.0.3
VSCode = 1.63.0

**Comment by Hamzelot** [comment]
After I restarted Visual Studio and the settings Deepl: Use Pro off, it works.

I think the description for the settings is confusing because when you create an account for Deepl you are thrown with terms like Deepl Pro.

**Comment by fengShuaiGe** [comment]
I have the same problem. it warns "Request failed with status code 403"

**Comment by UncleNanard** [comment]
Hello, same here. 403 :(
