### ISSUE TITLE
No translation to English GB/US

### ISSUE THREAD

**Issue by twsl** [soerenuhrbach/vscode-deepl#13]
I'm trying to translate a `hallo welt / hello world`, the dialog opens and closes without any error message.
I am trying to translate from `DE` to `EN-US` the other way around from `EN` to `DE` works
I can't seem to find any error message in neither the extensions output nor the developer console.
I'm using the free api and v1.0.3.

**Comment by soerenuhrbach** [comment]
Hi, 

I also noticed the same behavior a few months ago. 
It occurs when translating with source language detection (it's the default setting for using the "translate" command.)

It should work by using the command "translate from ... to ...".

At the moment I see no misbehaving  in this extension.. it's a thing on the api side of deepl.  

Let me know if you have any suggestions to improve this behavior.

Best regards
Sören

**Comment by twsl** [comment]
Using translate from to doesn't help. Apparently other languages are affected as well.

**Comment by twsl** [comment]
@soerenuhrbach any ETA? hmu, if you need any help

**Comment by soerenuhrbach** [comment]
Hi @twsl,

thanks for your contribution. I will test your changes in the upcoming week.
If everything works I will create a new release.
