### ISSUE TITLE
Doesn't work, no error message, have added the API key to the settings

### ISSUE THREAD

**Issue by philippthiele** [soerenuhrbach/vscode-deepl#21]
https://user-images.githubusercontent.com/1737722/164184706-a95261df-5339-4b6e-818c-0850741123d5.mp4

Just says shortly "Translating" at the lower right and nothing happens.

Unfortunately no error in the dev tools:
![image](https://user-images.githubusercontent.com/1737722/164185289-374d0e5e-4443-493c-a1d2-19349c897209.png)

**Comment by philippthiele** [comment]
![image](https://user-images.githubusercontent.com/1737722/164188175-0ae0a482-13a9-4724-8064-10b675625144.png)
detected source lang doesn't seem to work

**Comment by philippthiele** [comment]
source language detection seems to be very bad, I am trying to translate from german:
![image](https://user-images.githubusercontent.com/1737722/164188869-d3cc7348-25c3-498b-b0e4-bf6482f5a7cc.png)

**Comment by philippthiele** [comment]
When selecting the source language explicitely, it is working, I was putting too much hope on the auto detection

**Comment by philippthiele** [comment]
Created a PR to overcome the issue: https://github.com/soerenuhrbach/vscode-deepl/pull/22
This does two things:
- show a success message after translation, that lists the detected source languages
- puts the source language into state when it is once specified manually with alt+ctrl+shift+t

**Comment by soerenuhrbach** [comment]
Your fix is merged and released with version 1.0.5.
