### ISSUE TITLE
How can I edit the API key?

### ISSUE THREAD

**Issue by JuGuSm** [soerenuhrbach/vscode-deepl#47]
Hi, since the last update I cannot change my API key anymore on the settings and I don't find where it's stored.
My old key is no longer working but I have a new one.

**Comment by soerenuhrbach** [comment]
Hi @JuGuSm,

I just released version 1.0.13, which now provides a command to configure the extension:

<img width="636" alt="image" src="https://github.com/soerenuhrbach/vscode-deepl/assets/18682112/ca79ba00-7cab-49bf-ba77-b7222eeab705">

The new version should be available in a few minutes via the vscode marketplace.

**Comment by JuGuSm** [comment]
Great, it worked, thank you!

**Comment by JuGuSm** [comment]
fixed
