### ISSUE TITLE
v1.0.12 and v1.0.13 do not load properly

### ISSUE THREAD

**Issue by courchef** [soerenuhrbach/vscode-deepl#49]
Thanks for this extension!

I tried v1.0.13 and the extension is stuck in "loading state". The exact output is "Loading extension state...". See screenshot below. After trying older versions, I found out that v1.0.10 works fine, but v1.0.12 and v1.0.13 do not load at all on my Windows 10 computer.

![image](https://github.com/soerenuhrbach/vscode-deepl/assets/15271147/1a642a12-cb89-492c-8b8d-a3741ab54c11)

Here is the result when using v1.0.10

![image](https://github.com/soerenuhrbach/vscode-deepl/assets/15271147/d3c562ae-ec04-43ac-b066-3f4ff0ac168a)

VS Code information

Version: 1.86.2 (user setup)
Commit: 903b1e9d8990623e3d7da1df3d33db3e42d80eda
Date: 2024-02-13T19:40:56.878Z
Electron: 27.2.3
ElectronBuildId: 26908389
Chromium: 118.0.5993.159
Node.js: 18.17.1
V8: 11.8.172.18-electron.0
OS: Windows_NT x64 10.0.19045

**Comment by soerenuhrbach** [comment]
Hi, could you please try to set the api key using the "Deepl: Configure" command?

**Comment by courchef** [comment]
I forgot to specify that the "DeepL: Configure" command does not work either on my computer.

![image](https://github.com/soerenuhrbach/vscode-deepl/assets/15271147/5290664d-2d94-458d-b4c1-e3092690905d)

![image](https://github.com/soerenuhrbach/vscode-deepl/assets/15271147/087f28be-7367-4dba-bf46-78c646714104)

**Comment by soerenuhrbach** [comment]
There was a problem with initialising the extension state, if no api key was configured. 

The problem was fixed with the release of version 1.0.14.
