### ISSUE TITLE
entered wrong api key, how to change it

### ISSUE THREAD

**Issue by cedricwalter** [soerenuhrbach/vscode-deepl#50]
ive searched on disk but did not find it...
How to update the deep api key?

thanks

**Comment by uildriks** [comment]
I have the same problem, what is the solution?

**Comment by soerenuhrbach** [comment]
Hi @uildriks,

You can use the command "DeepL: Configure extension" to set your api key.

<img width="614" alt="image" src="https://github.com/soerenuhrbach/vscode-deepl/assets/18682112/d4ad3f49-b871-4b36-9d29-186040146548">
