### ISSUE TITLE
Add vscode setting for translation language

### ISSUE THREAD

**Issue by ietz** [soerenuhrbach/vscode-deepl#9]
I mostly use one target language, which I currently have to select again every time I restart VSCode. Would it be possible to add this as a setting variable, similar to `deepl.formality`? This way, one could specify a default translation language per user and workspace or leave the variable blank to retain the current behavior.

And thank you very much for publishing this extension! I love how I can select a section of text to translate directly in the document.

**Comment by soerenuhrbach** [comment]
Hi Tim, 

thanks a lot for your feedback!

I will try to improve the behavior asap!

**Comment by grandeljay** [comment]
Came here for this. It would be great to be able to set a default source/target language for a workspace!

**Comment by grandeljay** [comment]
> Well the thing is - it will be saved for the current workspace. If you open another workspace, then you have to set the target and source languages again.

That sounds great to me!

> Need some more time to think about the configuration hierarchy handling

In VS Code settings can be set per User and/or Workspace. So If you add an option for the default language, the user can always use their "global" default settings for languages. Unless they specify something else in their workspace settings.

**Comment by soerenuhrbach** [comment]
That sounds good to me. I will add two more settings for "defaultTargetLanguage" and "defaultSourceLanguage" to define global defaults.

**Comment by soerenuhrbach** [comment]
The new config options were released with version 1.0.7.
